language: php

sudo: false

php:
  - 5.5
  - 5.6
  - nightly
  - hhvm

matrix:
  fast_finish: true
  allow_failures:
    - php: nightly
    - php: hhvm

before_install:
  - composer self-update

install:
  - composer update --no-interaction --prefer-source --ignore-platform-reqs

script:
  - bin/phing ci-build
