services:
    vasek_purchart.tracy_blue_screen.blue_screen.controller_blue_screen_exception_listener:
        class: VasekPurchart\TracyBlueScreenBundle\BlueScreen\ControllerBlueScreenExceptionListener
        arguments:
            - @vasek_purchart.tracy_blue_screen.tracy.blue_screen
        tags:
            - { name: kernel.event_listener, event: kernel.exception }
